# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-editor.spec

# add or remove files that should be synced
files_to_sync:
    - rpm/deepin-editor.spec
    - .packit.yaml

upstream_package_name: deepin-editor
# downstream (Fedora) RPM package name
downstream_package_name: deepin-editor

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-editor.spec"
