.\" This file is processed to generate manpages in the
.\" build diretory.
.TH deepin-editor 1  "2020-11-17" "Deepin"
.SH NAME
deepin-editor \- the Text editor from UOS
.SH SYNOPSIS
.B deepin-editor
[\fIPATH\fR]
.SH DESCRIPTION
Text editor for DDE (Deepin Desktop Environment).
.PP
This program does not accept any command line options.
If the \fIPATH\fR is specified, open that file with .
If the \fIPATH\fR is omitted, open deepin-editor and show nothing.
If deepin-editor has been launched, open the Text with deepin-editor. 
Otherwise, launch deepin-editor and open the Text with it.
.SH SEE ALSO
https://www.deepin.org/en/original/deepin-editor/
.SH AUTHOR
.PP
.B deepin-editor
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT tuqinggang@\:uniontech.com
Tu Qinggang
.ME
for the Debian Project (but may be used by others).
