{
    "metadata" : {
        "revision" : 1,
        "name" : "Solarized Light",
        "author" : "Ethan Schoonover",
        "license" : "MIT",
        "read-only" : true
    },
    "text-styles": {
        "Normal" : {
            "text-color" : "#445257",
            "selected-bg-color" : "#586E75",
            "selected-text-color" : "#F2F2E2",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Keyword" : {
            "text-color" : "#1f1c1b",
            "selected-text-color" : "#ffffff",
            "bold" : true
        },
        "Function" : {
            "text-color" : "#644a9b",
            "selected-text-color" : "#452886"
        },
        "Variable" : {
            "text-color" : "#0057ae",
            "selected-text-color" : "#00316e"
        },
        "ControlFlow" : {
            "text-color" : "#1f1c1b",
            "selected-text-color" : "#ffffff",
            "bold" : true
        },
        "Operator" : {
            "text-color" : "#1f1c1b",
            "selected-text-color" : "#ffffff"
        },
        "BuiltIn" : {
            "text-color" : "#644a9b",
            "selected-text-color" : "#452886",
            "bold" : true
        },
        "Extension" : {
            "text-color" : "#0095ff",
            "selected-text-color" : "#ffffff",
            "bold" : true
        },
        "Preprocessor" : {
            "text-color" : "#006e28",
            "selected-text-color" : "#006e28"
        },
        "Attribute" : {
            "text-color" : "#0057ae",
            "selected-text-color" : "#00316e"
        },
        "Char" : {
            "text-color" : "#924c9d",
            "selected-text-color" : "#6c2477"
        },
        "SpecialChar" : {
            "text-color" : "#3daee9",
            "selected-text-color" : "#fcfcfc"
        },
        "String" : {
            "text-color" : "#bf0303",
            "selected-text-color" : "#9c0e0e"
        },
        "VerbatimString" : {
            "text-color" : "#bf0303",
            "selected-text-color" : "#9c0e0e"
        },
        "SpecialString" : {
            "text-color" : "#ff5500",
            "selected-text-color" : "#ff5500"
        },
        "Import" : {
            "text-color" : "#ff5500",
            "selected-text-color" : "#ff5500"
        },
        "DataType" : {
            "text-color" : "#0057ae",
            "selected-text-color" : "#00316e"
        },
        "DecVal" : {
            "text-color" : "#b08000",
            "selected-text-color" : "#805c00"
        },
        "BaseN" : {
            "text-color" : "#b08000",
            "selected-text-color" : "#805c00"
        },
        "Float" : {
            "text-color" : "#b08000",
            "selected-text-color" : "#805c00"
        },
        "Constant" : {
            "text-color" : "#aa5500",
            "selected-text-color" : "#5e2f00"
        },
        "Comment" : {
            "text-color" : "#898887",
            "selected-text-color" : "#5e5d5d"
        },
        "Documentation" : {
            "text-color" : "#607880",
            "selected-text-color" : "#46585e"
        },
        "Annotation" : {
            "text-color" : "#ca60ca",
            "selected-text-color" : "#a44ea4"
        },
        "CommentVar" : {
            "text-color" : "#0095ff",
            "selected-text-color" : "#ffffff"
        },
        "RegionMarker" : {
            "text-color" : "#0057ae",
            "selected-text-color" : "#00316e",
            "background-color" : "#e0e9f8"
        },
        "Information" : {
            "text-color" : "#b08000",
            "selected-text-color" : "#805c00"
        },
        "Warning" : {
            "text-color" : "#bf0303",
            "selected-text-color" : "#9c0e0e"
        },
        "Alert" : {
            "text-color" : "#bf0303",
            "selected-text-color" : "#9c0e0e",
            "background-color" : "#f7e6e6",
            "bold" : true
        },
        "Error" : {
            "text-color" : "#bf0303",
            "selected-text-color" : "#9c0e0e",
            "underline" : true
        },
        "Others" : {
            "text-color" : "#006e28",
            "selected-text-color" : "#006e28"
        }
   },
    "editor-colors": {
        "background-color" : "#FDF6E3",
        "code-folding" : "#224e65",
        "bracket-match-bg" : "#739099",
        "bracket-match-fg" : "#F2F2E2",
        "current-line" : "#EEE8D5",
        "icon-border" : "#31363b",
        "indentation-line" : "#3a3f44",
        "line-numbers" : "#7a7c7d",
        "current-line-number" : "#a5a6a8",
        "mark-bookmark" : "#0404bf",
        "mark-breakpoint-active" : "#8b0607",
        "mark-breakpoint-reached" : "#6d6e07",
        "mark-breakpoint-disabled" : "#820683",
        "mark-execution" : "#4d4e50",
        "mark-warning" : "#f67400",
        "mark-error" : "#da4453",
        "modified-lines" : "#c04900",
        "replace-highlight" : "#808021",
        "saved-lines" : "#1c8042",
        "find-match-background" : "#ffff00",
        "find-match-foreground" : "#000000",
        "find-highlight-background" : "#2CA7F8",
        "find-highlight-foreground" : "#FFFFFF",
        "selection" : "#224659",
        "separator" : "#7a7c7d",
        "spell-checking" : "#c0392b",
        "tab-marker" : "#4d4d4d",
        "template-background" : "#31363b",
        "template-placeholder" : "#123723",
        "template-focused-placeholder" : "#123723",
        "template-read-only-placeholder" : "#4d1f24",
        "word-wrap-marker" : "#3a3f44"
    },
    "app-colors" : {
        "tab-active" : "#403513",
        "tab-background-start-color" : "(253, 246, 227, 90%)",
        "tab-background-end-color" : "(245, 238, 220, 90%)",
        "tab-dnd-start" : "(238, 232, 213, 90%)",
        "tab-dnd-end" : "(238, 232, 213, 90%)",
        "themebar-frame-selected" : "#739099",
        "themebar-frame-normal" : "#000000"
    }
}
