// SPDX-FileCopyrightText: 2017 - 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.editor.daemon -a dbusadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusadaptor.h"

#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QMetaObject>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DaemonAdaptor
 */
DbusAdaptor::DbusAdaptor(QObject *parent) : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DbusAdaptor::~DbusAdaptor()
{
    // destructor
}

bool DbusAdaptor::saveFile(const QByteArray &filepath, const QByteArray &text, const QByteArray &encoding)
{
    // handle method call com.deepin.editor.daemon.saveFile.

    bool returnResult;
    QMetaObject::invokeMethod(parent(), "saveFile", Q_RETURN_ARG(bool, returnResult),
                              Q_ARG(QByteArray, filepath),
                              Q_ARG(QByteArray, text),
                              Q_ARG(QByteArray, encoding));

    return returnResult;
}
