// SPDX-FileCopyrightText: 2017 - 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.deepin.editor.daemon -a dbusadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSADAPTOR_H
#define DBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.editor.daemon
 */
class DbusAdaptor: public QDBusAbstractAdaptor {
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.editor.daemon")
    Q_CLASSINFO("D-Bus Introspection", ""
                "  <interface name=\"com.deepin.editor.daemon\">\n"
                "    <method name=\"saveFile\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"ay\" name=\"filepath\"/>\n"
                "      <arg direction=\"in\" type=\"ay\" name=\"text\"/>\n"
                "      <arg direction=\"in\" type=\"ay\" name=\"encoding\"/>\n"
                "    </method>\n"
                "  </interface>\n"
                "")
public:
    DbusAdaptor(QObject *parent);
    virtual ~DbusAdaptor();

public: // PROPERTIES

public Q_SLOTS: // METHODS
    bool saveFile(const QByteArray &filepath, const QByteArray &text, const QByteArray &encoding);

Q_SIGNALS: // SIGNALS
};

#endif
